/**
 * TimeVision API
 * API for TimeVision
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type GroupType = 0 | 1;

export const GroupType = {
    NUMBER_0: 0 as GroupType,
    NUMBER_1: 1 as GroupType
};