/**
 * TimeVision API
 * API for TimeVision
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InternalLevelDto { 
    id?: number;
    name?: string;
    cost?: number;
}