/**
 * TimeVision API
 * API for TimeVision
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupType } from './groupType';

export interface MinimalGroupDto { 
    id?: string;
    name?: string;
    type?: GroupType;
    isHierarchical?: boolean;
}