/**
 * TimeVision API
 * API for TimeVision
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InternalLevelDto } from './internalLevelDto';
import { Status } from './status';

export interface UserDto { 
    userId?: string;
    email?: string;
    tenantId?: string;
    firstName?: string;
    lastName?: string;
    status?: Status;
    hoursPerWeek?: number;
    hoursPerDay?: number;
    internalLevel?: InternalLevelDto;
    language?: string;
    country?: string; 
    chargeableGoal?: number;
}